### ISSUE TITLE
Python 2.7 support, but f-strings...

### ISSUE THREAD

**Issue by bharding512** [scivision/msise00#2]
Is Python 2.7 supported? I think the use of f-strings might preclude this. Hopefully I'm missing something.

**Comment by scivision** [comment]
The `future-fstrings` module seamlessly translates fstrings to old style strings.

    pip install future-fstrings

The support for Python 2.7 is withering off in the major numerical analysis packages. Already Ipython has had a few releases that are Python 3 only.
