### ISSUE TITLE
DLL Load Failure

### ISSUE THREAD

**Issue by jm52250** [scivision/msise00#4]
I was able to install and compile without any errors, but when I try to import the library I get the following error.

import msise00
Traceback (most recent call last):

  File "<ipython-input-8-d7e3367e95a0>", line 1, in <module>
    import msise00

  File "C:\Users\John\Anaconda3\lib\site-packages\msise00\__init__.py", line 16, in <module>
    import gtd7

ImportError: DLL load failed: The specified module could not be found.

I see the \gtd7\.libs folder with a dll in it.  Any thoughts on why msise00 does not see it?

**Comment by scivision** [comment]
@jm52250 I have changed the connection to MSIS fortran code. You shouldn't have this issue anymore in any case.
