### ISSUE TITLE
Linux installation UBUNTU 18.04 

### ISSUE THREAD

**Issue by macicco** [scivision/msise00#5]
Trying install it but lot of errors dont allow me to finish the procedure:
a - 
I did git clone and then inside the directory msise00, pip install -e. 
 something related to "undefined reference" to python scripts avoid the compilation run correctly
b -
![screenshot from 2019-01-21 14-37-25](https://user-images.githubusercontent.com/5925289/51487440-6e04a000-1d8a-11e9-81f5-45245a43dd17.png)

**Comment by scivision** [comment]
I'm not sure. I changed the prereqs to have Numpy &ge; 1.16 because I was getting 
> ModuleNotFoundError: No module named ‘numpy.core._multiarray_umath’
and this was fixed by [upgrading to Numpy 1.16](https://www.scivision.co/numpy-f2py-modulenotfound-multiarray-umath/)

**Comment by macicco** [comment]
After upgrading to Numpy 1.16, it worked nicely. Thanks!
Using Jupyter notebook, kernel 3.6 .
