### ISSUE TITLE
No attribute run

### ISSUE THREAD

**Issue by dp689** [scivision/msise00#6]
Hi, 

I'm following the simple example on pypi:

import msise00
from datetime import datetime

atmos = msise00.run(time=datetime(2013, 3, 31, 12), altkm=150., glat=65., glon=-148.)

But I'm being told msise80 has no attribute 'run'. Looking through the module folder I don't see anything about run,except in the base.py file as a function. I installed msise00 from the tar file.

**Comment by scivision** [comment]
HI @dp689 thanks for reaching out.

I just now tried
```python
import msise00
from datetime import datetime

atmos = msise00.run(time=datetime(2013, 3, 31, 12), altkm=150., glat=65., glon=-148.)
```
and it ran OK. 

I'm not sure what's happening, I'll try to take a look

**Comment by dp689** [comment]
After digging closer, I think the root problem is I didn't Install GCC, GFortran, CMake and Make on Windows (my OS).  I'm working on that now.

**Comment by scivision** [comment]
I realized the setup script is broken when installing from Pypi. I should have it fixed this afternoon.  Thanks so much for reporting!!

**Comment by dp689** [comment]
Oh awesome. Glad that works out. Let me know when it's all set and I'll try again?

**Comment by dp689** [comment]
Also, is the cmake file missing? There seems to be some issue installing everything with finding a suitable cmake file.

**Comment by scivision** [comment]
Thanks. I redid the setup for Matlab and Python (each are independent and optional).
Hope it works better, thanks for the help!!

Now after `pip install ...` you do one time from Python
```python
import msise00
msise00.build()
```

It will do that automatically on first run if you forget :-)

**Comment by scivision** [comment]
@dp689 hope it's better now. I tested on a Linux and Windows computer and it seems OK. I need to apply these techniques to similar repos I have (they don't affect MSIS). Thanks for your help.

**Comment by scivision** [comment]
there is a new release v1.4.0. The handling of data_files and the MSISE00 Fortran executable has been improved for and testing has been added for msise00 in virtual environments.
